### ISSUE TITLE
How to connect Node socket and SlimerJS socket?

### ISSUE THREAD

**Issue by Ivan-Parushev** [a-lucas/slimer.js-socket.io#1]
I know this is not the place to ask questions, but from my angle this looks like an issue. 
In the readme you have not elaborated much on how exactly to connect Node socket with SlimerJS using your repo. I have spend quite some time trying to do so...
Can you write a short description on how to use your script along with a Node socket?

**Comment by a-lucas** [comment]
You are so right, I have written this code a while ago, and I struggled to make it work.

You now have an [example](https://github.com/a-lucas/slimer.js-socket.io/tree/master/example) folder :) Don't forget to star if you find it useful.

When you create your io server, don't forget to attach it to a web server, so the file socket.io.js is available.
